# ----------------------------- SERVER ----------------------------- #

[server]
ManageUsername = "admin"
ManagePassword = "admin"
Port = "45222"

ReadTimeoutSeconds = 30
WriteTimeoutSeconds = 30

MaxShutdownTime = 5 # seconds

CORSAllowHeaders = ["Accept", "Authorization", "Content-Type", "Origin", "X-Requested-With"]
CORSAllowMethods = ["GET", "POST", "PUT", "DELETE"]
CORSAllowOrigins = ["http://127.0.0.1:45222", "http://localhost:45222"]

# ---------------------------- POSTGRES ---------------------------- #`

[postgres]
ConnAddress = "postgres://task_manager:task_manager@localhost/task_manager?sslmode=disable"

MaxOpenConns = 5
MaxIdleConns = 2

QueryTimeout = 60

# ---------------------------- LOOGERS  ---------------------------- #`

[logger]
FileName = "logs/app.log"
MaxSizeMb = 50
MaxBackups = 3
MaxAgeDays = 180